# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Problem1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_Input = QtWidgets.QGroupBox(Form)
        self.gb_Input.setObjectName("gb_Input")
        self.layout_GridInput = QtWidgets.QGridLayout(self.gb_Input)
        self.layout_GridInput.setObjectName("layout_GridInput")
        self.L_label = QtWidgets.QLabel(self.gb_Input)
        self.L_label.setObjectName("L_label")
        self.layout_GridInput.addWidget(self.L_label, 1, 0, 1, 1)
        self.L_input = QtWidgets.QLineEdit(self.gb_Input)
        self.L_input.setObjectName("L_input")
        self.layout_GridInput.addWidget(self.L_input, 1, 1, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gb_Input)
        self.R_label.setObjectName("R_label")
        self.layout_GridInput.addWidget(self.R_label, 2, 0, 1, 1)
        self.R_input = QtWidgets.QLineEdit(self.gb_Input)
        self.R_input.setObjectName("R_input")
        self.layout_GridInput.addWidget(self.R_input, 2, 1, 1, 1)
        self.C_label = QtWidgets.QLabel(self.gb_Input)
        self.C_label.setObjectName("C_label")
        self.layout_GridInput.addWidget(self.C_label, 3, 0, 1, 1)
        self.C_input = QtWidgets.QLineEdit(self.gb_Input)
        self.C_input.setObjectName("C_input")
        self.layout_GridInput.addWidget(self.C_input, 3, 1, 1, 1)
        self.Vm_label = QtWidgets.QLabel(self.gb_Input)
        self.Vm_label.setObjectName("Vm_label")
        self.layout_GridInput.addWidget(self.Vm_label, 4, 0, 1, 1)
        self.Vm_input = QtWidgets.QLineEdit(self.gb_Input)
        self.Vm_input.setObjectName("Vm_input")
        self.layout_GridInput.addWidget(self.Vm_input, 4, 1, 1, 1)
        self.freq_label = QtWidgets.QLabel(self.gb_Input)
        self.freq_label.setObjectName("freq_label")
        self.layout_GridInput.addWidget(self.freq_label, 5, 0, 1, 1)
        self.freq_input = QtWidgets.QLineEdit(self.gb_Input)
        self.freq_input.setObjectName("freq_input")
        self.layout_GridInput.addWidget(self.freq_input, 5, 1, 1, 1)
        self.phase_label = QtWidgets.QLabel(self.gb_Input)
        self.phase_label.setObjectName("phase_label")
        self.layout_GridInput.addWidget(self.phase_label, 6, 0, 1, 1)
        self.phase_input = QtWidgets.QLineEdit(self.gb_Input)
        self.phase_input.setObjectName("phase_input")
        self.layout_GridInput.addWidget(self.phase_input, 6, 1, 1, 1)
        self.simulate_button = QtWidgets.QPushButton(self.gb_Input)
        self.simulate_button.setObjectName("simulate_button")
        self.layout_GridInput.addWidget(self.simulate_button, 7, 0, 1, 2)
        self.image_label = QtWidgets.QLabel(self.gb_Input)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.layout_GridInput.addWidget(self.image_label, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.gb_Input)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gb_Input.setTitle(_translate("Form", "Input"))
        self.L_label.setText(_translate("Form", "L (H):"))
        self.L_input.setText(_translate("Form", "20"))
        self.R_label.setText(_translate("Form", "R (Ω):"))
        self.R_input.setText(_translate("Form", "10"))
        self.C_label.setText(_translate("Form", "C (F):"))
        self.C_input.setText(_translate("Form", "0.05"))
        self.Vm_label.setText(_translate("Form", "Voltage Magnitude (V):"))
        self.Vm_input.setText(_translate("Form", "20"))
        self.freq_label.setText(_translate("Form", "Frequency (rad/s):"))
        self.freq_input.setText(_translate("Form", "20"))
        self.phase_label.setText(_translate("Form", "Phase (rad):"))
        self.phase_input.setText(_translate("Form", "0"))
        self.simulate_button.setText(_translate("Form", "Simulate"))
